server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: user
    password: Pass123
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  application:
    context-path: /api/v1

