spring:
  application:
    name: cart-craft
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: user
    password: Pass123
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8081

api:
  prefix: /api/v1